disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - opening_brace
  - force_cast
  - identifier_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods



